targets:
  $default:
    builders:
      graphql_codegen:
        options:
          outputDirectory: "/lib/graphql/__gen"
          assetsPath: "lib/graphql/**.graphql"
          scalars:
            ISODateTime:
              type: String
            Json:
              type: dynamic
