name: myaniapp
description: A new Flutter project.

version: 0.2.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  # cupertino_icons: ^1.0.2
  auto_route: ^7.7.1
  cached_network_image: ^3.2.3
  graphql_flutter: ^5.1.2
  logger: ^1.4.0
  markdown: ^7.1.1
  markdown_widget: ^2.2.0
  html: ^0.15.4
  flutter_riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1
  intl: ^0.18.1
  timeago: ^3.5.0
  url_launcher: ^6.1.12
  dropdown_button2: ^2.3.7
  flutter_staggered_grid_view: ^0.6.2
  shared_preferences: ^2.2.0
  uni_links: ^0.5.1
  holding_gesture: ^1.1.0
  flutter_local_notifications: ^14.1.1
  http: ^1.1.0
  youtube_player_iframe: ^4.0.4
  workmanager: ^0.5.1
  google_mobile_ads: ^3.0.0
  uni_links_desktop: ^0.1.6

dependency_overrides:
  # both seem to use the same version but pub still errors
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  auto_route_generator: ^7.3.0
  build_runner: ^2.4.5
  graphql_codegen: ^0.13.5
  custom_lint: ^0.4.0
  riverpod_lint: ^1.3.2
  riverpod_generator: ^2.2.3
  flutter_launcher_icons: ^0.13.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter_launcher_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/android/play_store_512.png'
  web:
    generate: true
    image_path: 'assets/web/icon-512.png'
  windows:
    generate: true
    image_path: 'assets/web/icon-512.png'
    icon_size: 48 # min:48, max:256, default: 48

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
