name: myaniapp
description: A new Flutter project.
publish_to: none

version: 0.2.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  app_links: ^3.4.5
  built_collection: ^5.1.1
  cached_network_image: ^3.3.0
  collection: ^1.18.0
  ferry: ^0.14.2+1
  ferry_flutter: ^0.8.1
  ferry_hive_store: ^0.5.2
  fl_chart: ^0.66.0
  flutter:
    sdk: flutter
  flutter_local_notifications: ^16.1.0
  flutter_riverpod: ^2.4.3
  flutter_staggered_grid_view: ^0.7.0
  font_awesome_flutter: ^10.6.0
  go_router: ^13.0.0
  gql_http_link: ^1.0.1+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  holding_gesture: ^1.2.0
  html: ^0.15.4
  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.2+1
  markdown: ^7.1.1
  markdown_widget: ^2.2.0
  media_kit: ^1.1.10+1
  media_kit_libs_video: ^1.0.4
  media_kit_video: ^1.2.4
  riverpod_annotation: ^2.2.0
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  timeago: ^3.6.0
  url_launcher: ^6.1.14
  url_protocol:
    git:
      url: https://github.com/BillSchumacher/flutter_url_protocol.git
      ref: d765cfe
  workmanager: ^0.5.2
  youtube_player_iframe: ^4.0.4

dependency_overrides:
  win32: '>=4.0.0 <6.0.0'

dev_dependencies:
  build_runner: ^2.4.8
  custom_lint: ^0.5.3
  ferry_generator: ^0.8.1
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  # graphql_codegen: ^0.13.11
  riverpod_generator: ^2.3.3
  riverpod_lint: ^2.1.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter_launcher_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/android/play_store_512.png'
  web:
    generate: true
    image_path: 'assets/web/icon-512.png'
  windows:
    generate: true
    image_path: 'assets/web/icon-512.png'
    icon_size: 48 # min:48, max:256, default: 48

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
