name: myaniapp
description: "An unofficial Anilist app."
publish_to: "none"
version: 0.5.14

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  app_links: ^6.1.1
  cached_network_image: ^3.4.1
  collection: ^1.19.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_hooks: ^0.20.5
  flutter_local_notifications: ^18.0.1
  flutter_markdown: ^0.7.2+1
  flutter_riverpod: ^2.5.1
  gql: ^1.0.0+1
  gql_exec: ^1.0.0+1
  gql_http_link: ^1.1.0
  html: ^0.15.4
  http: ^1.2.1
  intl: ^0.19.0
  markdown: ^7.2.2
  markdown_widget: ^2.3.2+6
  package_info_plus: ^8.1.1
  relative_time: ^5.0.0
  shared_preferences: ^2.3.4
  url_launcher: ^6.2.5
  win32: ^5.5.1
  workmanager: ^0.5.2

  mygraphql:
    path: "./packages/mygraphql"
  hooks_riverpod: ^2.5.1
  gql_link: ^1.0.1-alpha+1717789143896
  numberpicker: ^2.1.2
  dots_indicator: ^3.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  ffi: any
  go_router: ^14.6.1
dev_dependencies:
  graphql_codegen: ^1.1.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.11
  custom_lint: ^0.7.0
  riverpod_lint: ^2.3.2
  flutter_launcher_icons: ^0.13.1
  icons_launcher: ^3.0.0

dependency_overrides:
  collection: 1.19.0

icons_launcher:
  image_path: "assets/app_icon.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
    windows:
      enable: true
    macos:
      enable: true
    linux:
      enable: true`

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/app_icon.png"
  windows:
    generate: true
    image_path: "assets/app_icon.png"
    icon_size: 192 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/app_icon.png
    - assets/tracking.png
