name: Build Linux

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Linux App
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[build]')
    permissions:
      contents: write

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Declare short sha
        shell: bash
        run: |
          echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"

      - name: Get Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.x'
          channel: 'stable'
          cache: true

      - name: Download deps
        run: |
          sudo apt update
          sudo apt install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev libstdc++-12-dev

      - run: flutter pub get
      - run: flutter build linux

      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: MyAniApp-${{ env.sha_short }}-linux-x64.zip
          directory: build/linux/x64/bundle

      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.sha_short }}
          artifacts: 'build/linux/x64/release/bundle/MyAniApp-${{ env.sha_short }}-linux-x64.zip'
          allowUpdates: true
          prerelease: true
