name: Build

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[build]')
    permissions:
      contents: write

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Get Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - run: flutter pub get
      - run: flutter build web --base-href /MyAniApp/

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
